## Data Frames

In [1]:
import pandas as pd
import numpy as np

In [8]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df1 = pd.DataFrame(data_list)
columns = ["Name","Age","City","salary"]
df1 = pd.DataFrame(data_list,columns = columns)
df1

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selction and indexing of column

In [15]:
df1

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
df1["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [19]:
df1[["Name","City"]] #For targeting two colums list ni andar list

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [21]:
df1["Designation"] = ["Doctor","Engineer","Teacher","Lawyar"]

In [22]:
df1

    Name  Age      City  salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000      Lawyar

# remove cloumns

In [37]:
df1

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# selecting row

In [38]:
df1.loc[0]

Name          John
Age             28
City      New York
salary       65000
Name: 0, dtype: object

In [40]:
df1.loc[[0,1]]

   Name  Age      City  salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

# selecting subsets and row of colums

In [47]:
df1.loc[[0,1]][["City","salary"]]

       City  salary
0  New York   65000
1     Paris   70000

In [48]:
df1.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

# conditional selection

In [49]:
df1

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [50]:
df1[df1['Age'] > 30]

    Name  Age    City  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [51]:
df1[(df1['Age'] > 30) & (df1['City'] == 'Paris')]

   Name  Age   City  salary
1  Anna   34  Paris   70000