In [1]:
import numpy as np
import pandas as pd

## Find missing Data

In [5]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
m1 = pd.DataFrame(data)
m1

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [7]:
m1.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [8]:
m1.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [9]:
m1

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [10]:
m1.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [11]:
m1.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [12]:
m1.fillna(1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  1.0
2  1.0  3  3.0  1.0
3  4.0  4  1.0  1.0
4  5.0  5  1.0  5.0

In [13]:
m1

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0